### PR TITLE
Coalesce - fixes #15

### LINKED ISSUE #15: Coalesce network writes
Right now, every response packet is written to the wire with `net.Conn.Write`. In applications where `GOMAXPROCS` is more than about 2, contention (and subsequent scheduler overhead) eat up a lot of performance.

I'd like to see monotonically improving performance with greater `GOMAXPROCS` up to the number of physical cores on the machine. Right now, on my laptop, `GOMAXPROCS=2` is *significantly* faster than `GOMAXPROCS=4` for the TCP case, and marginally faster for the other cases.

The issue here is that `net.Conn.Write` is the only way to guarantee to the caller that the message was actually sent. We can write into a buffer, which would probably improve performance quite a bit, but then callers wouldn't necessarily have a guarantee that requests/responses were written to the wire. Of course, the network itself doesn't provide much in the way of guarantees as it is, so maybe that's not a problem.

### PR DESCRIPTION
**Pull request by philhofer**
Still work-in-progress, but done enough to PR.

Writes on the client and server side are batched if possible. The performance improvements are really, really large.

[Review on Reviewable](https://reviewable.io/reviews/tinylib/synapse/17)

### CODE REVIEW

**Comment by ttacon** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tinylib/synapse/17)







---

<sup>**[client.go, line 266 \[r1\]](https://reviewable.io:443/reviews/tinylib/synapse/17#-JfhwPv1vXAuu_dVGn_M)** ([raw file](https://github.com/tinylib/synapse/blob/423f630875a596d501ff7a8740e8cf6e60bf1450/client.go#L266)):</sup>
Any reason for the stylistic difference between this line and the first case in the following select? (i.e. checking ok val vs if it was nil or not?)

---

<sup>**[client.go, line 300 \[r1\]](https://reviewable.io:443/reviews/tinylib/synapse/17#-JfhwyQd4msEaum6_g3C)** ([raw file](https://github.com/tinylib/synapse/blob/423f630875a596d501ff7a8740e8cf6e60bf1450/client.go#L300)):</sup>
I might be missing something, any reason this isn't != 0?

---

**Comment by ttacon** [comment]
Jeez, you got a lot done on this lol.

**Comment by philhofer** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/tinylib/synapse/17)







---

<sup>**[client.go, line 266 \[r1\]](https://reviewable.io:443/reviews/tinylib/synapse/17#-JfhwPv1vXAuu_dVGn_M)** ([raw file](https://github.com/tinylib/synapse/blob/423f630875a596d501ff7a8740e8cf6e60bf1450/client.go#L266)):</sup>
No good reason. I'll change that.

---

<sup>**[client.go, line 300 \[r1\]](https://reviewable.io:443/reviews/tinylib/synapse/17#-JfhwyQd4msEaum6_g3C)** ([raw file](https://github.com/tinylib/synapse/blob/423f630875a596d501ff7a8740e8cf6e60bf1450/client.go#L300)):</sup>
I agree; that reads better.

---

**Comment by philhofer** [comment]
I'm mostly happy with this, but I'm still working on figuring out how to close the output channel without racing.

**Comment by philhofer** [comment]
For now, I'm just using `sync.WaitGroup` for counting handlers. Fortunately, using it doesn't noticeably affect performance.

**Comment by philhofer** [comment]
So, a summary of final performance diffs, w/ `GOMAXPROCS=2` and `(*testing.Benchmark).SetParallelism(20)`:

| Benchmark | ns/op Before | ns/op After |
|:---------------:|:-----------------:|:---------------:|
| Client Pool | 9616 | 3678 |
| TCP Echo | 10716 | 2243 |
| Unix no-op | 3225 | 1591 | 
| Pipe no-op | 2745 | 1257 |

Hooray!

Moreover, now things get *marginally* (but consistently) faster in the `GOMAXPROCS=4` case, rather than significantly slower.

**Pull request merged**
